name: poppunk
owner: johnlees
remote_repository_url: https://github.com/johnlees/PopPUNK_galaxy/tree/master/PopPUNK
description: Clustering of bacterial genomes
long_description: |
   Fast and flexible bacterial genomic epidemiology with PopPUNK
   https://dx.doi.org/10.1101/gr.241455.118
categories: [Sequence Analysis]
